const DEFAULT_PROBLEM_RESULTS_TAKE_CONTESTS_PAGE = 10;

const CONTEST_PARTICIPATION_TYPES = {
    COMPETE: "compete",
    PRACTICE: "practice",
}

const CONTEST_RESULT_TYPES = {
    SIMPLE: "simple",
    FULL: "full",
}

export {
    DEFAULT_PROBLEM_RESULTS_TAKE_CONTESTS_PAGE,
    CONTEST_PARTICIPATION_TYPES,
    CONTEST_RESULT_TYPES,
};
