import { GridColDef } from '@mui/x-data-grid';

const dataColumns: GridColDef[] = [
    {
        field: 'id',
        headerName: 'Id',
        type: 'number',
        width: 10,
        filterable: true,
        sortable: true,
        valueFormatter: (params) => params.value.toString(),
    },
    {
        field: 'processed',
        headerName: 'Processed',
        align: 'center',
        type: 'boolean',
        width: 200,
        filterable: true,
        sortable: false,
    },
    {
        field: 'processing',
        headerName: 'Processing',
        align: 'center',
        type: 'boolean',
        width: 200,
        filterable: true,
        sortable: false,
    },
    {
        field: 'serializedException',
        headerName: 'Serialized Exception',
        align: 'center',
        width: 200,
        type: 'string',
        filterable: true,
        sortable: false,
    },
    {
        field: 'serializedExecutionDetails',
        headerName: 'Serialized Execution Details',
        align: 'center',
        width: 200,
        type: 'string',
        filterable: true,
        sortable: false,
    },
    {
        field: 'serializedExecutionResult',
        headerName: 'Serialized Execution Result',
        align: 'center',
        width: 200,
        type: 'string',
        filterable: true,
        sortable: false,
    },
    {
        field: 'submissionId',
        headerName: 'Submission ID',
        type: 'number',
        width: 200,
        filterable: true,
        sortable: true,
    },
    {
        field: 'createdOn',
        headerName: 'Created On',
        align: 'center',
        type: 'dateTime',
        width: 200,
        filterable: true,
        sortable: true,
    },
    {
        field: 'modifiedOn',
        headerName: 'Modified On',
        align: 'center',
        type: 'dateTime',
        width: 200,
        filterable: true,
        sortable: true,
    },
];

export default dataColumns;
