//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListByCategory_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListByCategory_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.Views.List.ListByCategory.bg", typeof(ListByCategory_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избраната категория е празна..
        /// </summary>
        public static string Category_is_empty {
            get {
                return ResourceManager.GetString("Category_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участвай.
        /// </summary>
        public static string Compete {
            get {
                return ResourceManager.GetString("Compete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултати от състезание.
        /// </summary>
        public static string Contest_results {
            get {
                return ResourceManager.GetString("Contest_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай състезание.
        /// </summary>
        public static string Create_contest {
            get {
                return ResourceManager.GetString("Create_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай състезания.
        /// </summary>
        public static string Edit_all_contests {
            get {
                return ResourceManager.GetString("Edit_all_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има парола.
        /// </summary>
        public static string Has_compete_password {
            get {
                return ResourceManager.GetString("Has_compete_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието е защитено с парола.
        /// </summary>
        public static string Has_practice_password {
            get {
                return ResourceManager.GetString("Has_practice_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импортирай състезания.
        /// </summary>
        public static string Import_contests {
            get {
                return ResourceManager.GetString("Import_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участници.
        /// </summary>
        public static string Participant_count {
            get {
                return ResourceManager.GetString("Participant_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практикувай.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултати от практика.
        /// </summary>
        public static string Practice_results {
            get {
                return ResourceManager.GetString("Practice_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой задачи.
        /// </summary>
        public static string Problems_count {
            get {
                return ResourceManager.GetString("Problems_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прехвърли.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
    }
}
