//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.ContestCategories.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsImportViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsImportViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.ContestCategories.ViewModels.Con" +
                            "testsImportViewModel", typeof(ContestsImportViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        public static string Api_key {
            get {
                return ResourceManager.GetString("Api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the API key for the chosen OJS Platform..
        /// </summary>
        public static string Api_key_required_error_message {
            get {
                return ResourceManager.GetString("Api_key_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contest IDs to Import.
        /// </summary>
        public static string Contest_ids {
            get {
                return ResourceManager.GetString("Contest_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comma or space-separated list of valid contest IDs..
        /// </summary>
        public static string Contest_ids_regex_error_message {
            get {
                return ResourceManager.GetString("Contest_ids_regex_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the contest IDs to import..
        /// </summary>
        public static string Contest_ids_required_error_message {
            get {
                return ResourceManager.GetString("Contest_ids_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OJS Platform URL.
        /// </summary>
        public static string Ojs_platform_url {
            get {
                return ResourceManager.GetString("Ojs_platform_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OJS Platform URL must be at least 10 characters long..
        /// </summary>
        public static string Ojs_platform_url_min_length_error_message {
            get {
                return ResourceManager.GetString("Ojs_platform_url_min_length_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the OJS Platform URL..
        /// </summary>
        public static string Ojs_platform_url_required_error_message {
            get {
                return ResourceManager.GetString("Ojs_platform_url_required_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace existing contests by matching their Name.
        /// </summary>
        public static string Replace_existing_contests {
            get {
                return ResourceManager.GetString("Replace_existing_contests", resourceCulture);
            }
        }
    }
}
