//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Problems.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailedProblem_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailedProblem_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Problems.ViewModels.DetailedProb" +
                            "lem.bg", typeof(DetailedProblem_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чекер.
        /// </summary>
        public static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезателни тестове.
        /// </summary>
        public static string Compete_tests {
            get {
                return ResourceManager.GetString("Compete_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезание.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стратегия по подразбиране.
        /// </summary>
        public static string DefaultSubmissionTypeName {
            get {
                return ResourceManager.GetString("DefaultSubmissionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група на задачи.
        /// </summary>
        public static string Group_number {
            get {
                return ResourceManager.GetString("Group_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум точки.
        /// </summary>
        public static string Max_points {
            get {
                return ResourceManager.GetString("Max_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум точките са задължителни!.
        /// </summary>
        public static string Max_points_required {
            get {
                return ResourceManager.GetString("Max_points_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит на памет.
        /// </summary>
        public static string Memory_limit {
            get {
                return ResourceManager.GetString("Memory_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимита на памет е задължителен!.
        /// </summary>
        public static string Memory_limit_required {
            get {
                return ResourceManager.GetString("Memory_limit_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максималната дължина е {1} символа!.
        /// </summary>
        public static string Name_length {
            get {
                return ResourceManager.GetString("Name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името е задължително!.
        /// </summary>
        public static string Name_required {
            get {
                return ResourceManager.GetString("Name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредба.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредбата е задължителна!.
        /// </summary>
        public static string Order_required {
            get {
                return ResourceManager.GetString("Order_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип на група от задачи.
        /// </summary>
        public static string Problem_group_type {
            get {
                return ResourceManager.GetString("Problem_group_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покажи пълния feedback.
        /// </summary>
        public static string Show_detailed_feedback {
            get {
                return ResourceManager.GetString("Show_detailed_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видими резултати.
        /// </summary>
        public static string Show_results {
            get {
                return ResourceManager.GetString("Show_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скелет.
        /// </summary>
        public static string Solution_skeleton {
            get {
                return ResourceManager.GetString("Solution_skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер на сорс кода.
        /// </summary>
        public static string Source_code_size_limit {
            get {
                return ResourceManager.GetString("Source_code_size_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит на време.
        /// </summary>
        public static string Time_limit {
            get {
                return ResourceManager.GetString("Time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимита на време е задължителен!.
        /// </summary>
        public static string Time_limit_required {
            get {
                return ResourceManager.GetString("Time_limit_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробни тестове.
        /// </summary>
        public static string Trial_tests {
            get {
                return ResourceManager.GetString("Trial_tests", resourceCulture);
            }
        }
    }
}
