FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# .Net build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dotnet_build

WORKDIR /src
COPY Servers/UI ./Servers/UI
COPY Servers/Infrastructure ./Servers/Infrastructure
COPY Services/UI ./Services/UI

COPY Directory.Build.props ./Directory.Build.props
COPY Analyzers ./Analyzers
COPY Common ./Common
COPY Data ./Data
COPY PubSub ./PubSub
COPY Services/Common ./Services/Common
COPY Services/Infrastructure ./Services/Infrastructure

# Dotnet Publish
FROM dotnet_build AS publish

WORKDIR /src/Servers/UI/OJS.Servers.Ui
RUN dotnet publish OJS.Servers.Ui.csproj -c Release -o /app/publish

# Dotnet Run
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
CMD dotnet OJS.Servers.Ui.dll
