//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Contests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsGeneral_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsGeneral_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Contests.ContestsGeneral.bg", typeof(ContestsGeneral_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е позволено качването на бинарни файлове..
        /// </summary>
        public static string Binary_files_not_allowed {
            get {
                return ResourceManager.GetString("Binary_files_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такава категория не съществува!.
        /// </summary>
        public static string Category_not_found {
            get {
                return ResourceManager.GetString("Category_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезавай се.
        /// </summary>
        public static string Compete {
            get {
                return ResourceManager.GetString("Compete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезание.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това състезание не е отворено за участие!.
        /// </summary>
        public static string Contest_cannot_be_competed {
            get {
                return ResourceManager.GetString("Contest_cannot_be_competed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това състезание не може да се практикува!.
        /// </summary>
        public static string Contest_cannot_be_practiced {
            get {
                return ResourceManager.GetString("Contest_cannot_be_practiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно състезание!.
        /// </summary>
        public static string Contest_not_found {
            get {
                return ResourceManager.GetString("Contest_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резултатите за това състезание не са достъпни!.
        /// </summary>
        public static string Contest_results_not_available {
            get {
                return ResourceManager.GetString("Contest_results_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно файлово разширение.
        /// </summary>
        public static string Invalid_extention {
            get {
                return ResourceManager.GetString("Invalid_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидни данни!.
        /// </summary>
        public static string Invalid_request {
            get {
                return ResourceManager.GetString("Invalid_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна селекция.
        /// </summary>
        public static string Invalid_selection {
            get {
                return ResourceManager.GetString("Invalid_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главни категории.
        /// </summary>
        public static string Main_categories {
            get {
                return ResourceManager.GetString("Main_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практика.
        /// </summary>
        public static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задачата не е част от вашите задачи за изпита.
        /// </summary>
        public static string Problem_not_assigned_to_user {
            get {
                return ResourceManager.GetString("Problem_not_assigned_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да бъде намерена задачата!.
        /// </summary>
        public static string Problem_not_found {
            get {
                return ResourceManager.GetString("Problem_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да видите резултата за тази задача!.
        /// </summary>
        public static string Problem_results_not_available {
            get {
                return ResourceManager.GetString("Problem_results_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класиране за {0} {1}.xls.
        /// </summary>
        public static string Report_excel_format {
            get {
                return ResourceManager.GetString("Report_excel_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този ресурс не може да бъде изтеглен!.
        /// </summary>
        public static string Resource_cannot_be_downloaded {
            get {
                return ResourceManager.GetString("Resource_cannot_be_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решението е качено..
        /// </summary>
        public static string Solution_uploaded {
            get {
                return ResourceManager.GetString("Solution_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не съществува такова решение!.
        /// </summary>
        public static string Submission_not_found {
            get {
                return ResourceManager.GetString("Submission_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това решение не е ваше!.
        /// </summary>
        public static string Submission_not_made_by_user {
            get {
                return ResourceManager.GetString("Submission_not_made_by_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратеният код е прекалено дълъг!.
        /// </summary>
        public static string Submission_too_long {
            get {
                return ResourceManager.GetString("Submission_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешен тип за оценяване на решението!.
        /// </summary>
        public static string Submission_type_not_found {
            get {
                return ResourceManager.GetString("Submission_type_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Решението е изпратено прекалено скоро!.
        /// </summary>
        public static string Submission_was_sent_too_soon {
            get {
                return ResourceManager.GetString("Submission_was_sent_too_soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не е позволено качването на текст.
        /// </summary>
        public static string Text_upload_not_allowed {
            get {
                return ResourceManager.GetString("Text_upload_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля качете файл..
        /// </summary>
        public static string Upload_file {
            get {
                return ResourceManager.GetString("Upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате необработено решение за този изпит. Моля изчакайте решението да бъде обработено..
        /// </summary>
        public static string User_has_not_processed_submission_for_contest {
            get {
                return ResourceManager.GetString("User_has_not_processed_submission_for_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате необработено решение за тази задача. Моля изчакайте решението да бъде обработено..
        /// </summary>
        public static string User_has_not_processed_submission_for_problem {
            get {
                return ResourceManager.GetString("User_has_not_processed_submission_for_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сте регистрирани за това състезание!.
        /// </summary>
        public static string User_is_not_registered_for_exam {
            get {
                return ResourceManager.GetString("User_is_not_registered_for_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
