//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests.Views.Partials {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestEditor_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestEditor_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.Views.Partials.ContestE" +
                            "ditor.bg", typeof(ContestEditor_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дали тестовете да имат детайлна обратна връзка според типа на съзтезанието (съзтезание/упражнение).
        /// </summary>
        public static string Auto_change_tests {
            get {
                return ResourceManager.GetString("Auto_change_tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете категория на състезанието.
        /// </summary>
        public static string Choose_category {
            get {
                return ResourceManager.GetString("Choose_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете край на състезанието.
        /// </summary>
        public static string Contest_end {
            get {
                return ResourceManager.GetString("Contest_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете подредба на състезанието.
        /// </summary>
        public static string Contest_order {
            get {
                return ResourceManager.GetString("Contest_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете парола на състезанието.
        /// </summary>
        public static string Contest_password {
            get {
                return ResourceManager.GetString("Contest_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете начало на състезанието.
        /// </summary>
        public static string Contest_start {
            get {
                return ResourceManager.GetString("Contest_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дали състезанието да бъде видимо.
        /// </summary>
        public static string Contest_visibility {
            get {
                return ResourceManager.GetString("Contest_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете продължителността на изпита в часове.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Времетраене.
        /// </summary>
        public static string Duration_info {
            get {
                return ResourceManager.GetString("Duration_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете описание на състезанието.
        /// </summary>
        public static string Enter_description {
            get {
                return ResourceManager.GetString("Enter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете заглавие на състезанието.
        /// </summary>
        public static string Enter_title {
            get {
                return ResourceManager.GetString("Enter_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основна информация.
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете броя на групи от задачи за онлайн състезание.
        /// </summary>
        public static string Number_of_problem_groups {
            get {
                return ResourceManager.GetString("Number_of_problem_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опции.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли.
        /// </summary>
        public static string Passowords_info {
            get {
                return ResourceManager.GetString("Passowords_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете край за упражнения.
        /// </summary>
        public static string Practice_end {
            get {
                return ResourceManager.GetString("Practice_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете парола за упражнения.
        /// </summary>
        public static string Practice_password {
            get {
                return ResourceManager.GetString("Practice_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете начало за упражнение.
        /// </summary>
        public static string Practice_start {
            get {
                return ResourceManager.GetString("Practice_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Може да променяте броя на групите от Администрацията за Групи Проблеми.
        /// </summary>
        public static string Problem_groups_edit_from_administration {
            get {
                return ResourceManager.GetString("Problem_groups_edit_from_administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видове решения.
        /// </summary>
        public static string Submission_types {
            get {
                return ResourceManager.GetString("Submission_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете лимит между изпращане на две последователни решения.
        /// </summary>
        public static string Submissions_limit {
            get {
                return ResourceManager.GetString("Submissions_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете дали потребителите могат да предават решения за различни задачи от състезанието едновременно.
        /// </summary>
        public static string Users_cant_submit_concurrently {
            get {
                return ResourceManager.GetString("Users_cant_submit_concurrently", resourceCulture);
            }
        }
    }
}
