const DEFAULT_ITEMS_PER_PAGE = 50;

const DEFAULT_ROWS_PER_PAGE = [ 15, 50, 100 ];

const COMPETE_STRING = 'COMPETE';
const PRACTICE_STRING = 'PRACTICE';

export {
    DEFAULT_ROWS_PER_PAGE,
    DEFAULT_ITEMS_PER_PAGE,
    PRACTICE_STRING,
    COMPETE_STRING,
};
