const DEFAULT_ITEMS_PER_PAGE = 10;

const DEFAULT_ROWS_PER_PAGE = [ 10, 25, 50, 100 ];

const DEFAULT_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss';

export {
    DEFAULT_ROWS_PER_PAGE,
    DEFAULT_ITEMS_PER_PAGE,
    DEFAULT_DATE_FORMAT,
};
