//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumTranslations_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumTranslations_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Common.Resources.Enums.EnumTranslations.bg", typeof(EnumTranslations_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторско решение.
        /// </summary>
        public static string AuthorsSolution {
            get {
                return ResourceManager.GetString("AuthorsSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По подразбиране.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown лист.
        /// </summary>
        public static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изключена от домашно.
        /// </summary>
        public static string Excluded_from_homework_problem_group {
            get {
                return ResourceManager.GetString("Excluded_from_homework_problem_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лаб.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многоредов текст.
        /// </summary>
        public static string MultiLineTextBox {
            get {
                return ResourceManager.GetString("MultiLineTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн практически изпит.
        /// </summary>
        public static string Online_practical_exam {
            get {
                return ResourceManager.GetString("Online_practical_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практически изпит на място.
        /// </summary>
        public static string Onsite_practical_exam {
            get {
                return ResourceManager.GetString("Onsite_practical_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отворен.
        /// </summary>
        public static string OpenTestDescription {
            get {
                return ResourceManager.GetString("OpenTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предстои изчисляване.
        /// </summary>
        public static string PendingSubmissionStatus {
            get {
                return ResourceManager.GetString("PendingSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условие.
        /// </summary>
        public static string ProblemDescription {
            get {
                return ResourceManager.GetString("ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчислен.
        /// </summary>
        public static string ProcessedSubmissionStatus {
            get {
                return ResourceManager.GetString("ProcessedSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Практически изпит на място с рандом задачи.
        /// </summary>
        public static string Random_tasks_onsite_practical_exam {
            get {
                return ResourceManager.GetString("Random_tasks_onsite_practical_exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезателен.
        /// </summary>
        public static string StandardTestDescription {
            get {
                return ResourceManager.GetString("StandardTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Едноредов текст.
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нулев.
        /// </summary>
        public static string TrialTestDescription {
            get {
                return ResourceManager.GetString("TrialTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
