//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestAdministration_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestAdministration_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.ViewModels.ContestAdmin" +
                            "istration.bg", typeof(ContestAdministration_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволени IP-та.
        /// </summary>
        public static string Allowed_ips {
            get {
                return ResourceManager.GetString("Allowed_ips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматично определяне на видимостта на детайлната обратна връзка на тестовете.
        /// </summary>
        public static string Auto_change_tests_feedback_visibility {
            get {
                return ResourceManager.GetString("Auto_change_tests_feedback_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на категорията.
        /// </summary>
        public static string Category_name {
            get {
                return ResourceManager.GetString("Category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорията е задължителна!.
        /// </summary>
        public static string Category_required {
            get {
                return ResourceManager.GetString("Category_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола за състезание.
        /// </summary>
        public static string Contest_password {
            get {
                return ResourceManager.GetString("Contest_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип уъркър по подразбиране.
        /// </summary>
        public static string Default_worker_type {
            get {
                return ResourceManager.GetString("Default_worker_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължителност.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край.
        /// </summary>
        public static string End_time {
            get {
                return ResourceManager.GetString("End_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреди за липсващи авторски решения.
        /// </summary>
        public static string EnsureValidAuthorSubmisions {
            get {
                return ResourceManager.GetString("EnsureValidAuthorSubmisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позволената дължина е между {2} и {1} символа.
        /// </summary>
        public static string Name_length {
            get {
                return ResourceManager.GetString("Name_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името е задължително!.
        /// </summary>
        public static string Name_required {
            get {
                return ResourceManager.GetString("Name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой групи от задачи.
        /// </summary>
        public static string Number_of_problem_groups {
            get {
                return ResourceManager.GetString("Number_of_problem_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредба.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подредбата е задължителна!.
        /// </summary>
        public static string Order_required {
            get {
                return ResourceManager.GetString("Order_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата не може да бъде по-дълга от {1} символа.
        /// </summary>
        public static string Password_max_length {
            get {
                return ResourceManager.GetString("Password_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Край упражнение.
        /// </summary>
        public static string Practice_end_time {
            get {
                return ResourceManager.GetString("Practice_end_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола за упражнение.
        /// </summary>
        public static string Practice_password {
            get {
                return ResourceManager.GetString("Practice_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало упражнение.
        /// </summary>
        public static string Practice_start_time {
            get {
                return ResourceManager.GetString("Practice_start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        public static string Start_time {
            get {
                return ResourceManager.GetString("Start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип решения.
        /// </summary>
        public static string Submision_types {
            get {
                return ResourceManager.GetString("Submision_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Време между събмисии.
        /// </summary>
        public static string Submissions_limit {
            get {
                return ResourceManager.GetString("Submissions_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителите не могат да решават задачи едновременно.
        /// </summary>
        public static string UsersCantSubmitConcurrently {
            get {
                return ResourceManager.GetString("UsersCantSubmitConcurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видимост.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видим от.
        /// </summary>
        public static string VisibleFrom {
            get {
                return ResourceManager.GetString("VisibleFrom", resourceCulture);
            }
        }
    }
}
