//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Administration.Contests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContestsControllers_bg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContestsControllers_bg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OJS.Web.App_GlobalResources.Areas.Administration.Contests.ContestsControllers.bg", typeof(ContestsControllers_bg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието е активно и продължителността и типа не могат да се променят!.
        /// </summary>
        public static string Active_contest_cannot_edit_duration_type {
            get {
                return ResourceManager.GetString("Active_contest_cannot_edit_duration_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието е активно и не може да бъде изтрито!.
        /// </summary>
        public static string Active_contest_forbidden_for_deletion {
            get {
                return ResourceManager.GetString("Active_contest_forbidden_for_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието е активно и не може да се местят участници.
        /// </summary>
        public static string Active_contest_forbidden_for_transfer {
            get {
                return ResourceManager.GetString("Active_contest_forbidden_for_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно добавихте {0} минути към времената на всички избрани активни участници в състезанието {1}.
        /// </summary>
        public static string Added_time_to_participants_online {
            get {
                return ResourceManager.GetString("Added_time_to_participants_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно добавихте {0} минути към времeто на участник с потребителско име: {1}, в състезанието {2}.
        /// </summary>
        public static string Added_time_to_single_participant_online {
            get {
                return ResourceManager.GetString("Added_time_to_single_participant_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието беше добавено успешно.
        /// </summary>
        public static string Contest_added {
            get {
                return ResourceManager.GetString("Contest_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието беше променено успешно.
        /// </summary>
        public static string Contest_edited {
            get {
                return ResourceManager.GetString("Contest_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Състезанието не е намерено.
        /// </summary>
        public static string Contest_not_found {
            get {
                return ResourceManager.GetString("Contest_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно състезание.
        /// </summary>
        public static string Contest_not_valid {
            get {
                return ResourceManager.GetString("Contest_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Началната дата на състезанието не може да бъде след крайната дата на състезанието.
        /// </summary>
        public static string Contest_start_date_before_end {
            get {
                return ResourceManager.GetString("Contest_start_date_before_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продължителността трябва да е във формат &quot;hh:mm&quot;.
        /// </summary>
        public static string Duration_invalid_format {
            get {
                return ResourceManager.GetString("Duration_invalid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;ВНИМАНИЕ: Продължителността на състезанието на следните потребители не беше обновена, защото продължителността им би паднала под базовата продължителност на състезанието: {0}.
        /// </summary>
        public static string Failed_to_update_participants_duration {
            get {
                return ResourceManager.GetString("Failed_to_update_participants_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма активни състезания.
        /// </summary>
        public static string No_active_contests {
            get {
                return ResourceManager.GetString("No_active_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма бъдещи състезания.
        /// </summary>
        public static string No_future_contests {
            get {
                return ResourceManager.GetString("No_future_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нямa последни състезaния.
        /// </summary>
        public static string No_latest_contests {
            get {
                return ResourceManager.GetString("No_latest_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не може да се намери въпрос по зададеното Id.
        /// </summary>
        public static string No_question_by_id {
            get {
                return ResourceManager.GetString("No_question_by_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участникът не фигурира в състезанието!.
        /// </summary>
        public static string Participant_not_in_contest {
            get {
                return ResourceManager.GetString("Participant_not_in_contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участниците са преместени успешно!.
        /// </summary>
        public static string Participants_transferred {
            get {
                return ResourceManager.GetString("Participants_transferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Началната дата за упражнения не може да бъде след крайната дата за упражнения.
        /// </summary>
        public static string Practice_start_date_before_end {
            get {
                return ResourceManager.GetString("Practice_start_date_before_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Броят на групи проблеми не може да бъде повече от {0}.
        /// </summary>
        public static string Problem_groups_count_limit {
            get {
                return ResourceManager.GetString("Problem_groups_count_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} решения за {0}.zip.
        /// </summary>
        public static string Report_zip_format {
            get {
                return ResourceManager.GetString("Report_zip_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително за състезание с рандом задачи.
        /// </summary>
        public static string Required_field_for_contest_with_random_tasks {
            get {
                return ResourceManager.GetString("Required_field_for_contest_with_random_tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето е задължително за Онлайн състезание.
        /// </summary>
        public static string Required_field_for_online {
            get {
                return ResourceManager.GetString("Required_field_for_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изберете поне един вид решение!.
        /// </summary>
        public static string Select_one_submission_type {
            get {
                return ResourceManager.GetString("Select_one_submission_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно отнехте {0} минути от времената на всички избрани активни участници в състезанието {1}.
        /// </summary>
        public static string Subtracted_time_from_participants_online {
            get {
                return ResourceManager.GetString("Subtracted_time_from_participants_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно отнехте {0} минути от времето на участник с потребителско име: {1},  в състезанието {2}.
        /// </summary>
        public static string Subtracted_time_from_single_participant_online {
            get {
                return ResourceManager.GetString("Subtracted_time_from_single_participant_online", resourceCulture);
            }
        }
    }
}
