const selectors = {
    pageSingleTaskFromSideNavigationSelector: '.all-tasks-list li',
    pageSideNavigationTitleSelector: '.navigationContest div h2',
    pageContestNavigationSelector: '.navigationContest',
    pageSubmissionBoxSelector: '.submissionBox',
    pageContestControlsSelector: '.contestTabControls',
    pageContestScoreSelector: '.score strong',
    pageContestRemainingTimeSelector: '.remainingTime',
    pageExecutionTypeSelectorActiveSelector: '.executionTypeSelectorActive',
    pageExecutionTypeSelectorInactiveSelector: '.executionTypeSelectorInactive',
    pageRefreshSubmissionButtonSelector: '.refreshButton',
    pageExecutionTypeActiveSelector: '.executionTypeSelectorActive',
    pageContestNavigationLiSelector: '.navigationContest li',
    pageSubmitButtonSelector: 'button*=Submit',
    pageSubmissionLabel: '.label',
    pageSubmissionTabs: '.contestTabs',
    pageSubmissionResultConteiner: '.contestTabControls',
    pageCurrentChosenTaskTitle: 'submissionBox h2 span',
    pageSubmissionResultInPoints: '.submissionResult',
    pageStrategyTypePerSubmission: '.currentSubmissionType',
    pageLeftNavgationResultsBtn: '.navigationContest a',
    pageSubmissionResultsNoResultsParagraph: '.submissionResultsContent p',
};
export default selectors;
