const selectors = {
    pageHeaderHeadingSelector: '#page-header-h2',
    pageFooterSelector: '#pageFooter',
    pageHeaderLogoLinkSelector: '#page-header-h2 a',
    pageHeadingImageSelector: '#page-header-h2 a img',
    pageLogInButtonSelector: '#anonymous-login-link',
    pageRegisterButtonSelector: '#anonymous-register-link',
    pageNavContestsLinkSelector: '#nav-contests-link',
    pageNavSubmissionssLinkSelector: '#nav-submissions-link',
    pageYoutubeVideoSelector: '#youtube-video',
    pageSeeActiveContestsButtonSelector: '.btn-see-all-contests-active',
    pageSeePastContestsButtonSelector: '.btn-see-all-contests-past',
    pageCardControlsSelector: '.card-control-buttons',
    pageAllActiveCardsSelector: '.active-contests-cards-list',
    pageAllPastCardsSelector: '.past-contests-cards-list',
    pageContestCardClassSelector: '.card-contests',
    pageContestCardHeaderSelector: '.card-header',
    pageContestCardCategorySelector: '.card-category',
    pageContestCardTimeTextSelector: '.card-counter p',
    pageContestCardTimerSelector: '.card-counter',
    pageCompeteButtonIdSelector: '#button-card-compete',
    pagePracticeButtonIdSelector: '#button-card-practice',
};
export default selectors;
