name: 05. Deploy FE (Development)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      branch_name:
        description: 'The branch that will be deployed'
        required: false
        type: string
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_image_name: judge_web_fe
      dockerfile_name: Dockerfile.fe
      docker_tag: dev-latest
      branch_name: ${{ inputs.branch_name || 'v2-development' }}
      build_args: YARN_BUILD_COMMAND=build:staging
      additional_run_commands: |
        export NODE_OPTIONS=--max-old-space-size=8192
    secrets: inherit
  deploy:
    needs: [build-and-push]
    uses: ./.github/workflows/deploy.yml
    secrets:
      webhook_url: ${{ secrets.FE_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      docker_username: ${{ secrets.SOFTUNIBUILD_USER }}
      docker_password: ${{ secrets.SOFTUNIBUILD_PAT }}
